#!/usr/bin/env bash
# Exercises check-coverage.sh against synthetic cover profiles in a
# throwaway git repository.
set -euo pipefail

script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/check-coverage.sh"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

# run PROFILE [ENV...]: sets $out and $code.
run() {
  local profile="$1"
  shift
  set +e
  out="$(env "$@" bash "$script" "$profile" 2>&1)"
  code=$?
  set -e
}

expect() {
  case "$out" in
    *"$1"*) ;;
    *) fail "expected '$1' in output, got: $out" ;;
  esac
}

reject() {
  case "$out" in
    *"$1"*) fail "unexpected '$1' in output: $out" ;;
  esac
}

cd "$work"
git init -q
mkdir -p cmd/relay internal/a internal/b internal/gen
printf 'module example.com/m\n\ngo 1.26\n' >go.mod
printf 'package main\n' >cmd/relay/main.go
printf 'package a\n' >internal/a/a.go
printf 'package b\n' >internal/b/b.go
printf '// Code generated by tool. DO NOT EDIT.\n\npackage gen\n' >internal/gen/gen.go

m=example.com/m
cat >pass.out <<EOF
mode: atomic
$m/cmd/relay/main.go:1.1,9.1 50 0
$m/internal/a/a.go:1.1,2.1 9 1
$m/internal/a/a.go:3.1,4.1 1 0
$m/internal/b/b.go:1.1,2.1 17 4
$m/internal/b/b.go:3.1,4.1 3 0
$m/internal/gen/gen.go:1.1,2.1 40 0
EOF

run pass.out
[ "$code" -eq 0 ] || fail "expected exit 0, got $code: $out"
expect "internal/a                                 90.0%  (9/10)"
expect "internal/b                                 85.0%  (17/20)"
expect "total                                      86.7%  (26/30)"
reject "cmd/relay"
reject "internal/gen"
reject "below"

run pass.out COVERAGE_TOTAL_MIN=87
[ "$code" -eq 1 ] || fail "expected exit 1 below the total floor, got $code"
expect "total                                      86.7%  (26/30)  below 87%"

run pass.out COVERAGE_PACKAGE_MIN=86
[ "$code" -eq 1 ] || fail "expected exit 1 below the package floor, got $code"
expect "internal/b                                 85.0%  (17/20)  below 86%"
reject "internal/a                                 90.0%  (9/10)  below"

# Blocks repeated across test binaries count once, covered if any run hit them.
cat >dup.out <<EOF
mode: set
$m/internal/a/a.go:1.1,2.1 9 0
$m/internal/a/a.go:3.1,4.1 1 0
$m/internal/a/a.go:1.1,2.1 9 1
$m/internal/a/a.go:3.1,4.1 1 0
EOF
run dup.out
[ "$code" -eq 0 ] || fail "expected exit 0 for deduplicated blocks, got $code: $out"
expect "internal/a                                 90.0%  (9/10)"

cat >excluded-only.out <<EOF
mode: set
$m/cmd/relay/main.go:1.1,9.1 50 0
EOF
run excluded-only.out
[ "$code" -eq 2 ] || fail "expected exit 2 with no countable statements, got $code: $out"

run missing.out
[ "$code" -eq 2 ] || fail "expected exit 2 for a missing profile, got $code"
expect "cover profile not found"

set +e
bash "$script" >/dev/null 2>&1
code=$?
set -e
[ "$code" -eq 2 ] || fail "expected exit 2 without arguments, got $code"

echo "ok"
